config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup'}, controllers: { confirmations: 'confirmations' }
  
  resources :products do
    resources :comments
  end

  resources :users do
    resources :comments
    resources :orders do
      resources :order_products
    end
  end

  # post 'users/:user_id/orders/:order_id/products/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  # delete 'users/:user_id/orders/:order_id/products/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'
  
  #payments
  post 'payments/create', to: 'payments#create'

  
  #root
  root 'products#index'
  

  # static_pages routes
  get 'static_pages/', to: 'static_pages#index' 

  get 'static_pages/index'

  get 'static_pages/about'

  get 'static_pages/contact', to: 'static_pages#contact'

  post 'static_pages/thank_you', to: 'static_pages#thank_you'

  get 'branches', to: 'branches#coordinates'
  #----------------------------------------------------------------

  # orders routes
  # delete 'orders/:id/:product_id', to: 'orders#remove_product', as: 'remove_product_from_order'
  #----------------------------------------------------------------

  
  get 'static_pages/page_404', to: 'static_pages#page_404'

  #I want to redirect every not specified route into some page ()
  match "*path", to: 'static_pages#no_route', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
# order model
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products
  has_many :products, through: :order_products
  belongs_to :status

  validates :user, presence: true

  def total_cost
    sum = 0
    products.each do |product|
      sum += product.price_in_cents
    end
    sum
  end

  def deliver
    update(status: Status.delivered)
  end

  def cancel
    update(status: Status.canceled)
  end

  def delivered
    update(status: Status.delivered)
  end

  scope :canceled, -> { where('status_id = ?', Status.canceled.id) }
  scope :delivered, -> { where('status_id = ?', Status.delivered.id) }
  scope :active, -> { where('status_id = ?', Status.active.id) }

  def total_cost_in_dollars
    cost = total_cost
    cents = (cost % 100).to_s
    cents = '0' + cents if cents.to_s.length == 1
    (cost / 100).to_s + '.' + cents
  end
end

app/controllers/orders_controller.rb
# orders controller
class OrdersController < ApplicationController
  before_action :set_order, except: [:index]
  before_action :authenticate_user!
  load_and_authorize_resource :user
  load_and_authorize_resource :order, through: :user

  # GET /orders
  # GET /orders.json
  def index
    @orders = if current_user.admin?
                Order.all
              else
                Order.all.where('user_id = ?', @user.id)
              end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show; end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      notice_message = 'Order was successfully destroyed.'
      u_id = @user.id
      format.html { redirect_to user_orders_url(u_id), notice: notice_message }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  rescue ActiveRecord::ActiveRecordError
    redirect_to root_url, alert: 'No valid ID provided to show the object'
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def order_params
    params.require(:order).permit(:user_id)
  end
end

app/helpers/orders_helper.rb
# orders helper module
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true, class: 'margin-bottom-md') do |form| %>
  <div class="field form-group">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :order_user_id, class: 'form-control'%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_index.html.erb
<% orders ||= @orders %>
<section class="container margin-bottom-md">
  <header>
    <h1>Orders</h1>
  </header>

  <table class="table">
    <thead>
      <tr>
        <th>Order ID</th>
        <%= "<th>User ID</th>".html_safe if current_user.admin? %>
        <%= "<th>User full name</th>".html_safe if current_user.admin? %>
        <th>Status</th>
        <th>Total Cost</th>
        <th>Operations</th>
      </tr>
    </thead>

    <tbody>
      <% orders.each do |order| %>
        <tr>
          <td><%= order.id %></td>
            <%= ("<td>" + order.user.id.to_s + "</td>").html_safe if current_user.admin? %>
            <%= ("<td>" + order.user.full_name + "</td>").html_safe if current_user.admin? %>
          <td><%= order.status.status_type %></td>
          <td>$<%= order.total_cost_in_dollars %></td>
          <td class="text-center">
            <% if order.status.status_type == 'active'%>
              <%= link_to 'Pay With Card', [@user, order], class: 'btn btn-success'%>
            <% end %>
            <% if current_user.admin? %>
              <%= link_to 'Destroy', [@user, order], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%#= link_to 'New Order', new_order_path, class: 'btn btn-primary' %>

</section><!-- end - Orders Dashboard -->

app/views/orders/_show.html.erb
<section class="container margin-bottom-md" >
  <header>
    <h2>
      <%= "This Order's ID: " + @order.id.to_s %>
    </h2>
  </header>

  <table class="table">
    <thead>
      <tr>
        <th>Product Name</th>
        <th>Price</th>
        <th colspan="3">Operations</th>
      </tr>
    </thead>
    <tbody>
      <% @order.order_products.each do |order_product| %>
        <tr>
          <td><%= order_product.product.name %></td>
          <td><%= order_product.product.price %></td>
          <td><%= link_to 'Delete', [@user, @order, order_product], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% if @order.order_products.length > 0 %>
    <%= form_with(url: payments_create_url, method: :post ) do |form| %>
      <%= render partial: "shared/stripe_checkout_button" %>
    <% end %>
  <% end %>
  <br>
  <%= link_to 'Orders Dashboard', user_orders_path(@user.id), class: 'btn btn-primary' %>

</section><!-- end - show single order -->

app/views/orders/edit.html.erb
<section class="container margin-bottom-md">
  <header>
    <h1>Editing Order</h1>
  </header>

  <%= render 'form', order: @order %>

  <%= link_to 'Show', @order, class: 'btn btn-primary' %> |
  <%= link_to 'Orders Dashboard', orders_path, class: 'btn btn-primary' %>

</section><!-- end - edit order -->

app/views/orders/index.html.erb
<%= render partial: 'index' %>

app/views/orders/new.html.erb
<section class="container margin-bottom-md">
  <header>
    <h1>New Order</h1>
  </header>

  <%= render 'form', order: @order, class: 'btn btn-primary' %>

  <%= link_to 'Orders Dashboard', orders_path, class: 'btn btn-primary' %>

</section><!-- end - add new order form -->

app/views/orders/show.html.erb
<%= render partial: 'show' %>