config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup'}, controllers: { confirmations: 'confirmations' }
  
  resources :products do
    resources :comments
  end

  resources :users do
    resources :comments
    resources :orders do
      resources :order_products
    end
  end

  # post 'users/:user_id/orders/:order_id/products/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  # delete 'users/:user_id/orders/:order_id/products/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'
  
  #payments
  post 'payments/create', to: 'payments#create'

  
  #root
  root 'products#index'
  

  # static_pages routes
  get 'static_pages/', to: 'static_pages#index' 

  get 'static_pages/index'

  get 'static_pages/about'

  get 'static_pages/contact', to: 'static_pages#contact'

  post 'static_pages/thank_you', to: 'static_pages#thank_you'

  get 'branches', to: 'branches#coordinates'
  #----------------------------------------------------------------

  # orders routes
  # delete 'orders/:id/:product_id', to: 'orders#remove_product', as: 'remove_product_from_order'
  #----------------------------------------------------------------

  
  get 'static_pages/page_404', to: 'static_pages#page_404'

  #I want to redirect every not specified route into some page ()
  match "*path", to: 'static_pages#no_route', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>H-ASH PC Store</title>

    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-header">
        <%= link_to 'H-ASH', root_path, class: "navbar-brand" %>
        <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#links-navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle Navbar</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="links-navbar-collapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to ('<span class="badge badge-notify">' + current_user.active_order.products.length.to_s +  '</span>').html_safe, user_order_path(current_user.id, current_user.active_order.id), class: 'glyphicon glyphicon-shopping-cart'%></li>
          <% end %>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Contact Us', static_pages_contact_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to 'Dashboard', user_path(current_user.id) %></li>
            <% if current_user.admin? %>
              <li><%= link_to 'Orders Dashboard', user_orders_path(current_user.id)%></li>
              <li><%= link_to 'Products Dashboard', products_path%></li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </nav><!-- end - navbar -->
    <% if user_signed_in? %>
      <script>localStorage.setItem('user_id', '<%= current_user.id %>');</script>
    <% else %>
      <script>localStorage.removeItem('user_id');</script>
    <% end %>
    <section class="container-fluid">
      <% if (notice && notice.length != 0) %>
        <%= render partial: 'shared/notice', locals: {type: 'success', message: notice}%>
      <% elsif (alert && alert.length != 0) %>
        <%= render partial: 'shared/notice', locals: {type: 'danger', message: alert}%>
      <% end %>
      <% if flash && flash[:error] %>
        <%= render partial: 'shared/errors_flash', locals: {errors: flash[:error], model: flash[:model] }%>
      <% end %>
    </section><!-- end - flash messages -->
    <div class="notification-popup">
    </div><!-- end - notifications popup -->
    <div id="user-buttons" class="input-group<%= " logged-in-widget" if user_signed_in? %>">
      <div class="input-group-btn">
        <button class="btn btn-primary glyphicon glyphicon-user"></button>
        <% if user_signed_in? %>
          <p class="form-control"><%= current_user.email %></p>
          <%= link_to('', destroy_user_session_path, method: :delete, class: 'btn btn-primary glyphicon glyphicon-log-out') %>
        <% else %>
          <%= link_to('', new_user_session_path, class: 'btn btn-primary glyphicon glyphicon-log-in') %>
          <%= link_to('', new_user_registration_path, class: 'btn btn-primary glyphicon glyphicon-plus') %>
        <% end %>
      </div>
    </div><!-- end - user-specific buttons (login/sighup) -->

    <%= yield %> <!-- end - content filled by ruby (yeild) -->
    
    <% cache do %>
      <footer class="container-fluid">
        Copyright &copy; 2017, Hamza Ashour
      </footer><!-- end - footer -->
    <% end %>
  </body>
</html>